### PR TITLE
absolute url for fetch

### LINKED ISSUE #11: "Uncaught SyntaxError: Unexpected reserved word" is reported at getColors.js:5
with Chrome Version 88.0.4324.182 (Official Build) (32-bit), https://mdn.github.io/js-examples/modules/top-level-await/ fails to load as expected with the error as title reported. Same with Fire Fox 85.0.2 (64-bit).

Looks like "export default await colors;" has some issue with the usage of await here.

can you please have a look?

### PR DESCRIPTION
**Pull request by Rumyra**
Should fix #11

Would like to test after merge if I can

### CODE REVIEW

**Review by Ewelkaka — APPROVED** [review]

File: modules/top-level-await/modules/getColors.js [hunk 1]
```diff
@@ -1,5 +1,5 @@
 // fetch request
-const colors = fetch('/modules/top-level-await/data/colors.json')
+const colors = fetch('https://mdn.github.io/js-examples/modules/top-level-await/data/colors.json')
 	.then(response => response.json());
```
Comment (robert2104-tech) [inline modules/top-level-await/modules/getColors.js]: Idk
